# Generated by Django 4.1.3 on 2022-11-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Useradd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('accounts', models.BooleanField(default=False)),
                ('hr', models.BooleanField(default=False)),
                ('sales', models.BooleanField(default=False)),
                ('purchase', models.BooleanField(default=False)),
                ('reports', models.BooleanField(default=False)),
            ],
        ),
    ]
